#!/bin/sh

# owlrun
# ----------------
# Copyright : (c) 2015, Steve Zdancewic <steve.zdancewic@gmail.org>
# Licence   : BSD3
#
# This file is a part of owl.


# create the owl directory (if it doesn't already exist)
mkdir -p ~/Documents/OwlCode

# make sure that the .ocamlinit file exists 
cat > ~/Documents/OwlCode/.ocamlinit << EOF
(* Added by OPAM. *)
let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;
#use "topfind";;
#load "graphics.cma";;
#require "owl";;
#load "owl.cma";;
EOF

cd ~/Documents/OwlCode/
owl
